baseURL = "http://kathra.io/"
languageCode = "en-us"
title = "Kathra"
theme = "timer-hugo"

# We Used Ionicons Icon font for Icon, for more details check this link - https://ionicons.com/

# Site Menus
[menu]
    # Navbar Menus
    [[menu.nav]]
        name    = "News"
        url     = "/news"
        weight  = 1
    [[menu.nav]]
        name    = "Get Started"
        url     = "/get-started"
        weight  = 2
    [[menu.nav]]
        name    = "Demo"
        url     = "/demo"
        weight  = 3
    [[menu.nav]]
        name    = "Community"
        url     = "/community"
        weight  = 4
    [[menu.nav]]
        name    = "About us"
        url     = "/aboutus"
        weight  = 5
    [[menu.nav]]
        name    = "git"
        url     = "/git"
        weight  = 6


# Site Params
[params]
    home = "Home"
    logo = "images/logo.png"
    dateFormat = "6 January 2006"
    # Meta data
    description = "Kathra"
    author = "Kathra"
    # Google Analitycs
    googleAnalitycsID = "Your ID"

    # Banner Section
    [params.banner]
        enable  = false
        bgImage = ""
        heading = ""
        description = "KATHRA is the first tool to help you automatically generate, build, deploy, and run code, all from an API specification."
        btn     = false
        btnText = "Get Started"
        btnURL  = "http://localhost:1313"

    [params.latestnewsbanner]
        enable  = true
    
    # Homepage About Section
    [params.about]
        enable  = true
        title   = ""
        content = "KATHRA is the first tool to help you automatically generate, build, deploy, and run code, all from an API specification."
        image   = ""

    # Call to Action
    [params.cta]
        enable  = false
        title   = "SO WHAT DO YOU THINK ?"
        content = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nobis,<br>possimus commodi, fugiat magnam temporibus vero magni recusandae? Dolore, maxime praesentium."
        btnText = "Contact Us"
        btnURL  = "/contact"

    # Portfolio Section On Homepage
    [params.portfolio]
        enable  = false
        title   = "Latest Works"
        subtitle= "Aliquam lobortis. Maecenas vestibulum mollis diam. Pellentesque auctor neque nec urna. Nulla sit amet est. Aenean posuere tortor sed cursus feugiat, nunc augue blandit nunc, eu sollicitudin urna dolor sagittis lacus."

    # Feature Product Section
    [params.featureProduct]
        enable  = false
        title   = "SOME OF OUR FEATURES WORKS"
        subtitle= "Aliquam lobortis. Maecenas vestibulum mollis diam. Pellentesque auctor neque nec urna. Nulla sit amet est. Aenean posuere <br> tortor sed cursus feugiat, nunc augue blandit nunc, eu sollicitudin urna dolor sagittis lacus."

    