#baseURL = "https://www.kathra.org/"
languageCode = "en-us"
title = "Kathra"
theme = "timer-hugo"
relativeurls = true
# We Used Ionicons Icon font for Icon, for more details check this link - https://ionicons.com/


DefaultContentLanguage = "en"
copyright = "Everything is mine"

[languages]
  [languages.en]
    title = "Kathra"
    weight = 1
  [languages.fr]
    title = "Kathra"
    weight = 2

# Site Menus
[menu]
    # Navbar Menus
    [[menu.nav]]
        name    = "News"
        url     = "/news"
        weight  = 1
    [[menu.nav]]
        name    = "Product"
        url     = "#features-anchor"
        weight  = 2
    [[menu.nav]]
        name    = "Demo"
        url     = "#demo-anchor"
        weight  = 3
    [[menu.nav]]
        name    = "Get Started"
        url     = "#gettingstarted-anchor"
        weight  = 4
    [[menu.nav]]
        name    = "Source Code"
        url     = "https://gitlab.com/kathra"
        weight  = 5
    [[menu.nav]]
        name    = "Road Map"
        url     = "#roadmap-anchor"
        weight  = 6
    [[menu.nav]]
        name    = "Partners"
        url     = "#partners-anchor"
        weight  = 7




# Site Params
[params]
    home = "Home"
    logo = "images/logo.png"
    dateFormat = "6 January 2006"
    # Meta data
    description = "Kathra"
    author = "Kathra"
    # Google Analitycs
    googleAnalitycsID = "Your ID"

    # Banner Section
    [params.banner]
        enable  = false
        bgImage = ""
        heading = ""
        description = "KATHRA is the first tool to help you automatically generate, build, deploy, and run code, all from an API specification."

    [params.gettingstarted]
        enable  = true
      
    [params.latestnewsbanner]
        enable  = true
    
    # Homepage About Section
    [params.about]
        enable  = true
        title   = ""
        content = "KATHRA is the first tool to help you automatically generate, build, deploy, and run code, all from an API specification."
        image   = "images/kathra-screenshot.png"
        btnText = "Get Started"
        btnURL  = "http://localhost:1313"

    # Homepage features Section
    [params.features]
        enable  = true

    # Homepage demo Section
    [params.demo]
        enable  = true
        title   = "Intrigued ? come and see how kathra works"
        btnText = "try the demo"
        btnURL  = "http://localhost:1313"

    # Homepage roadmap Section
    [params.roadmap]
        enable  = true
        title   = "Road Map"
        btnText = "see the roadmap"
        btnURL  = "http://localhost:1313"

    [params.partners]
        enable  = true
        title   = "Partners"
        
    [params.cta]
        enable  = false
        title   = "SO WHAT DO YOU THINK ?"
        content = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nobis,<br>possimus commodi, fugiat magnam temporibus vero magni recusandae? Dolore, maxime praesentium."
        btnText = "Contact Us"
        btnURL  = "/contact"

    # Portfolio Section On Homepage
    [params.portfolio]
        enable  = false
        title   = "Latest Works"
        subtitle= "Aliquam lobortis. Maecenas vestibulum mollis diam. Pellentesque auctor neque nec urna. Nulla sit amet est. Aenean posuere tortor sed cursus feugiat, nunc augue blandit nunc, eu sollicitudin urna dolor sagittis lacus."

    # Feature Product Section
    [params.featureProduct]
        enable  = false
        title   = "SOME OF OUR FEATURES WORKS"
        subtitle= "Aliquam lobortis. Maecenas vestibulum mollis diam. Pellentesque auctor neque nec urna. Nulla sit amet est. Aenean posuere <br> tortor sed cursus feugiat, nunc augue blandit nunc, eu sollicitudin urna dolor sagittis lacus."

    
